/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpgc.rpg129669;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
